# Generated by Django 2.1.4 on 2020-10-15 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('remote_ip', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='Vĩ độ / latitude')),
                ('longitude', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='Kinh độ / longitude')),
            ],
            options={
                'verbose_name': 'Lượng tải về',
                'verbose_name_plural': 'Lượng tải về',
                'db_table': 'd_app_tracking',
            },
        ),
    ]
