#!/usr/bin/env bash
source ~/app/production/venv/bin/activate
cd ~/app/production/tetviet/src/tetviet/
python manage.py createsupereditor --username kt2_editor_nguyendiendung --password nguyendiendung@kt2 --noinput --email nguyendiendung@kt2.com
python manage.py createsupereditor --username kt2_editor_dongthithuy --password dongthithuy@kt2 --noinput --email dongthithuy@kt2.com
python manage.py createsupereditor --username kt2_editor_nguyentuananh --password nguyentuananh@kt2 --noinput --email nguyentuananh@kt2.com
python manage.py createsupereditor --username kt2_editor_ngovanthoan --password ngovanthoan@kt2 --noinput --email ngovanthoan@kt2.com
python manage.py createsupereditor --username kt2_editor_tranminhphuc --password tranminhphuc@kt2 --noinput --email tranminhphuc@kt2.com
python manage.py createsupereditor --username kt3_editor_congthithuhang --password congthithuhang@kt3 --noinput --email congthithuhang@kt3.com
python manage.py createsupereditor --username kt3_editor_nguyenthininh --password nguyenthininh@kt3 --noinput --email nguyenthininh@kt3.com
python manage.py createsupereditor --username kt3_editor_nguyenducngoc --password nguyenducngoc@kt3 --noinput --email nguyenducngoc@kt3.com
python manage.py createsupereditor --username kt3_editor_phamanhduc --password phamanhduc@kt3 --noinput --email phamanhduc@kt3.com
python manage.py createsupereditor --username kt3_editor_dinhngoclan --password dinhngoclan@kt3 --noinput --email dinhngoclan@kt3.com
python manage.py createsupereditor --username kt3_editor_nguyenngocson --password nguyenngocson@kt3 --noinput --email nguyenngocson@kt3.com
python manage.py createsupereditor --username kt3_editor_trantronghoan --password trantronghoan@kt3 --noinput --email trantronghoan@kt3.com
python manage.py createsupereditor --username kt3_editor_luuthihuyentrang --password luuthihuyentrang@kt3 --noinput --email luuthihuyentrang@kt3.com
python manage.py createsupereditor --username kt3_editor_nguyenphuongbac --password nguyenphuongbac@kt3 --noinput --email nguyenphuongbac@kt3.com
python manage.py createsupereditor --username kt6_editor_dothienthietson --password dothienthietson@kt6 --noinput --email dothienthietson@kt6.com
python manage.py createsupereditor --username kt6_editor_luuvanphuong --password luuvanphuong@kt6 --noinput --email luuvanphuong@kt6.com
python manage.py createsupereditor --username kt6_editor_levanhoang --password levanhoang@kt6 --noinput --email levanhoang@kt6.com
python manage.py createsupereditor --username kt6_editor_nguyenthanhlong --password nguyenthanhlong@kt6 --noinput --email nguyenthanhlong@kt6.com
python manage.py createsupereditor --username kt6_editor_tathingocanh --password tathingocanh@kt6 --noinput --email tathingocanh@kt6.com
python manage.py createsupereditor --username kt8_editor_phamvietvan --password phamvietvan@kt8 --noinput --email phamvietvan@kt8.com
python manage.py createsupereditor --username kt8_editor_nguyenchivan --password nguyenchivan@kt8 --noinput --email nguyenchivan@kt8.com
python manage.py createsupereditor --username kt8_editor_nguyenmanhthang --password nguyenmanhthang@kt8 --noinput --email nguyenmanhthang@kt8.com
python manage.py createsupereditor --username kt8_editor_nguyenminhthich --password nguyenminhthich@kt8 --noinput --email nguyenminhthich@kt8.com
python manage.py createsupereditor --username kt8_editor_nguyenmanhhung --password nguyenmanhhung@kt8 --noinput --email nguyenmanhhung@kt8.com
python manage.py createsupereditor --username kt8_editor_duongtronghue --password duongtronghue@kt8 --noinput --email duongtronghue@kt8.com
python manage.py createsupereditor --username kt8_editor_nguyenanhtuan --password nguyenanhtuan@kt8 --noinput --email nguyenanhtuan@kt8.com
python manage.py createsupereditor --username kt8_editor_nguyenviettuan --password nguyenviettuan@kt8 --noinput --email nguyenviettuan@kt8.com
python manage.py createsupereditor --username kt9_editor_dinhquangdung --password dinhquangdung@kt9 --noinput --email dinhquangdung@kt9.com
python manage.py createsupereditor --username kt9_editor_doanduykhanh --password doanduykhanh@kt9 --noinput --email doanduykhanh@kt9.com
python manage.py createsupereditor --username kt9_editor_ngokhacbao --password ngokhacbao@kt9 --noinput --email ngokhacbao@kt9.com
python manage.py createsupereditor --username kt9_editor_phamthicamlequynh --password phamthicamlequynh@kt9 --noinput --email phamthicamlequynh@kt9.com
python manage.py createsupereditor --username kt9_editor_vutronghuynh --password vutronghuynh@kt9 --noinput --email vutronghuynh@kt9.com
python manage.py createsupereditor --username kt9_editor_nguyenvanson --password nguyenvanson@kt9 --noinput --email nguyenvanson@kt9.com
python manage.py createsupereditor --username kt10_editor_trieunhuhoa --password trieunhuhoa@kt10 --noinput --email trieunhuhoa@kt10.com
python manage.py createsupereditor --username kt10_editor_nguyenthuhong --password nguyenthuhong@kt10 --noinput --email nguyenthuhong@kt10.com
python manage.py createsupereditor --username kt10_editor_dothitonga --password dothitonga@kt10 --noinput --email dothitonga@kt10.com
python manage.py createsupereditor --username kt10_editor_nguyenvietphuong --password nguyenvietphuong@kt10 --noinput --email nguyenvietphuong@kt10.com
